# Generated by Django 5.2.7 on 2025-10-21 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Select the language for this book', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.language'),
        ),
    ]
